version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: puppetdb
      PGDATA: /var/lib/postgresql/data/pgdata 
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
