version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: puppetdb
      PGDATA: /var/lib/postgresql/data/pgdata 
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  puppet:
    image: puppet/puppetserver:latest
    container_name: puppet
    restart: always
    volumes:
      - ./puppetserver/puppetcode:/etc/puppetlabs/code/
      - ./puppetserver/puppetca:/etc/puppetlabs/puppetserver/ca
      - ./puppetserver/puppetconfig:/etc/puppetlabs/puppet/
      - ./puppetserver/puppetdata:/opt/puppetlabs/server/data/puppetserver/
    ports:
      - 8140:8140
      - 8170:8170
  puppetdb:
    image: puppet/puppetdb:latest
    container_name: puppetdb
    restart: always
    ports:
      - 32771:8080

volumes:
  puppetcode:
  puppetconfig:
  puppetca:
  puppetdata:
  postgres: